

import 'package:firebase_messaging/firebase_messaging.dart';



class NotificationHandler {
  
  static Future<String?> registerOnFirebase(
      FirebaseMessaging? firebaseMessaging) async {
    try {
      await FirebaseMessaging.instance
          .setForegroundNotificationPresentationOptions(
        alert: true,
        badge: true,
        sound: true,
      );
      firebaseMessaging?.requestPermission(
        alert: true,
        announcement: true,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );
      firebaseMessaging?.subscribeToTopic('all');
      //retrive token it is unique generated by the FCM server when the app registers for push notifications
      String? notificationToken;
      notificationToken = await firebaseMessaging?.getToken();
      if (notificationToken != null) {
        return notificationToken;
      }
    } catch (ex) {
      throw Exception(ex.toString());
    }
    return null;
  }


  // static Future<void> firebaseMessagingForegroundHandler() async {
  //   FirebaseMessaging.onMessage.listen((RemoteMessage message) {
  //     NotificationManager().notifications.insert(0,message);
  //   });
  // }
}
